apiVersion: v1
kind: Pod
metadata:
  name: placesapp
  labels:
    app: placesapp
spec:
  containers:
    - name: placesapp
      image: timbobb/placesapp:tagVersion
      ports:
        - containerPort: 8080
