apiVersion: apps/v1
kind: Deployment
metadata:
  name: placesapp
  labels:
    app: placesapp
spec:
  containers:
    - name: placesapp
      image: docker.io/timbobb/placesapp:tagVersion
      ports:
        - containerPort: 8080
  restartPolicy: Always
