apiVersion: v1
kind: Pod
metadata:
  name: placesapp
  labels:
    app: placesapp

spec:
  selector:
    matchLabels:
      app: placesapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: placesapp
        tier: frontend
    spec:
      containers:
      - name: placesapp
        image: docker.io/timbobb/placesapp:tagVersion
        ports:
        - containerPort: 8080
          name: placesapp
    restartPolicy: Always