apiVersion: v1
kind: Pod
metadata:
  name: placesapp
  labels:
    app: placesapp
spec:
  containers:
    - name: placesapp:tagVersion
      image: docker.io/timbobb/placesapp:tagVersion
      ports:
        - containerPort: 8080
  restartPolicy: Always
