apiVersion: v1
kind: Pod
metadata:
  name: placesapp
  labels:
    app: placesapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: Recreate
  
spec:
  containers:
    - name: placesapp
      image: docker.io/timbobb/placesapp:tagVersion
      ports:
        - containerPort: 8080
  restartPolicy: Always
